In [1]:
import pandas as pd
import numpy as np

In [2]:
traindata = pd.read_csv('/Users/chungpinhsu/Downloads/train.csv')
traindata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 785 entries, label to pixel783
dtypes: int64(785)
memory usage: 251.5 MB


In [3]:
from sklearn.model_selection import train_test_split
train_label = traindata.iloc[0:10001, 0:1]
train_image = traindata.iloc[0:10001, 1:]
train_image_trainimage, train_image_testimage, train_label_trainlabel, train_label_testlabel = train_test_split(train_image, train_label, random_state=0)

In [4]:
from sklearn import svm
clf = svm.SVC()
clf.fix(train_image_trainimage, train_label_trainlabel)
clf.predict(train_image_testimage)


AttributeError: 'SVC' object has no attribute 'fix'

In [5]:
from sklearn import svm
clf = svm.SVC()
clf.fit(train_image_trainimage, train_label_trainlabel)
clf.predict(train_image_testimage)

/Users/chungpinhsu/anaconda3/envs/ds/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 1, 1, ..., 1, 1, 1])

In [6]:
clf.score(train_image_trainimage, train_label_trainlabel)

1.0

In [7]:
from sklearn import svm
clf = svm.SVC()
clf.fit(train_image_trainimage, train_label_trainlabel.values.ravel())
clf.predict(train_image_testimage)

array([1, 1, 1, ..., 1, 1, 1])

In [8]:
clf.score(train_image_trainimage, train_label_trainlabel)

1.0

In [9]:
clf.score(train_image_testimage, train_label_testlabel)

0.1135545781687325

In [10]:
clf = svm.SVC(kernel = 'rbf')
clf.fit(train_image_trainimage, train_label_trainlabel.values.ravel())
clf.predict(train_image_testimage)

array([1, 1, 1, ..., 1, 1, 1])

In [11]:
clf.score(train_image_testimage, train_label_testlabel)

0.1135545781687325

In [12]:
clf = svm.SVC(kernel = 'linear')
clf.fit(train_image_trainimage, train_label_trainlabel.values.ravel())
clf.predict(train_image_testimage)

array([5, 6, 2, ..., 9, 7, 6])

In [13]:
clf.score(train_image_testimage, train_label_testlabel)

0.91203518592562971

In [14]:
train_label = traindata.iloc[0:5001, 0:1]
train_image = traindata.iloc[0:5001, 1:]
train_image_trainimage, train_image_testimage, train_label_trainlabel, train_label_testlabel = train_test_split(train_image, train_label, random_state=0)

In [15]:
clf = svm.SVC(kernel = 'linear')
clf.fit(train_image_trainimage, train_label_trainlabel.values.ravel())
clf.predict(train_image_testimage)

array([1, 6, 8, ..., 0, 2, 7])

In [16]:
clf.score(train_image_testimage, train_label_testlabel)

0.91446842525979222

In [17]:
train_label = traindata.iloc[0:3001, 0:1]
train_image = traindata.iloc[0:3001, 1:]
train_image_trainimage, train_image_testimage, train_label_trainlabel, train_label_testlabel = train_test_split(train_image, train_label, random_state=0)

In [18]:
clf = svm.SVC(kernel = 'linear')
clf.fit(train_image_trainimage, train_label_trainlabel.values.ravel())
clf.predict(train_image_testimage)

array([3, 8, 7, 1, 8, 5, 7, 8, 6, 1, 1, 2, 0, 2, 1, 6, 9, 4, 8, 7, 7, 6, 0,
       7, 2, 2, 9, 7, 4, 2, 6, 4, 4, 1, 5, 7, 8, 1, 9, 6, 1, 2, 7, 2, 5, 7,
       5, 4, 1, 2, 8, 2, 0, 3, 3, 5, 5, 0, 8, 2, 6, 9, 6, 5, 5, 2, 5, 4, 8,
       1, 4, 2, 5, 7, 3, 6, 9, 4, 9, 1, 4, 8, 2, 7, 6, 7, 4, 5, 6, 2, 7, 0,
       5, 7, 0, 1, 6, 2, 5, 1, 6, 5, 2, 9, 2, 1, 2, 0, 2, 3, 0, 9, 9, 0, 3,
       4, 9, 9, 0, 7, 7, 7, 0, 7, 4, 8, 2, 7, 2, 9, 4, 0, 0, 4, 1, 1, 1, 5,
       4, 9, 0, 2, 8, 1, 9, 4, 1, 0, 7, 7, 6, 5, 4, 0, 6, 0, 0, 2, 1, 3, 6,
       2, 9, 0, 1, 5, 0, 0, 5, 3, 6, 5, 9, 2, 6, 6, 8, 5, 8, 6, 4, 0, 3, 1,
       3, 0, 7, 2, 2, 6, 1, 2, 7, 8, 1, 1, 1, 6, 0, 6, 8, 3, 3, 5, 5, 4, 7,
       1, 6, 3, 2, 6, 8, 7, 1, 0, 5, 4, 9, 9, 1, 2, 1, 1, 2, 8, 3, 2, 4, 2,
       4, 2, 3, 7, 9, 3, 1, 0, 1, 4, 8, 9, 7, 5, 8, 5, 9, 6, 7, 7, 4, 4, 0,
       4, 4, 5, 6, 8, 6, 0, 3, 0, 3, 9, 1, 8, 6, 1, 4, 2, 6, 3, 3, 5, 5, 2,
       5, 9, 1, 3, 6, 2, 6, 2, 4, 7, 5, 2, 6, 8, 4, 9, 4, 6, 1, 7, 4, 1, 0,
       4, 5,

In [19]:
clf.score(train_image_testimage, train_label_testlabel)

0.92276964047936083

In [20]:
train_label = traindata.iloc[0:1501, 0:1]
train_image = traindata.iloc[0:1501, 1:]
train_image_trainimage, train_image_testimage, train_label_trainlabel, train_label_testlabel = train_test_split(train_image, train_label, random_state=0)

In [21]:
clf = svm.SVC(kernel = 'linear')
clf.fit(train_image_trainimage, train_label_trainlabel.values.ravel())
clf.predict(train_image_testimage)

array([6, 3, 1, 0, 7, 8, 5, 8, 0, 6, 0, 9, 1, 9, 8, 8, 7, 0, 4, 9, 1, 4, 8,
       9, 5, 1, 3, 9, 1, 8, 2, 6, 8, 9, 6, 1, 2, 5, 8, 6, 0, 8, 8, 5, 8, 1,
       6, 1, 5, 9, 2, 5, 3, 7, 2, 0, 6, 8, 1, 3, 7, 4, 4, 7, 8, 7, 2, 5, 5,
       9, 7, 4, 0, 0, 0, 9, 2, 9, 1, 9, 1, 5, 9, 2, 8, 3, 1, 3, 2, 1, 6, 2,
       2, 3, 3, 8, 3, 2, 9, 7, 3, 1, 4, 8, 0, 0, 5, 4, 5, 0, 8, 0, 9, 6, 1,
       6, 6, 3, 6, 9, 1, 8, 2, 7, 1, 0, 5, 4, 0, 9, 7, 9, 6, 8, 2, 7, 6, 0,
       5, 3, 0, 2, 1, 5, 0, 9, 2, 6, 5, 0, 4, 1, 2, 1, 2, 7, 0, 2, 1, 9, 5,
       5, 3, 8, 7, 5, 0, 6, 9, 9, 2, 4, 5, 7, 9, 6, 3, 1, 3, 1, 1, 6, 1, 1,
       9, 8, 0, 5, 4, 4, 8, 2, 2, 7, 0, 6, 1, 5, 7, 2, 0, 6, 2, 1, 2, 2, 0,
       7, 0, 3, 8, 3, 0, 6, 2, 9, 6, 2, 7, 0, 5, 9, 2, 4, 0, 0, 3, 6, 7, 9,
       2, 5, 7, 7, 5, 5, 2, 9, 9, 4, 5, 6, 7, 1, 2, 5, 0, 1, 5, 6, 4, 2, 1,
       8, 5, 3, 1, 8, 3, 5, 6, 4, 6, 4, 2, 3, 7, 1, 2, 9, 1, 1, 7, 6, 8, 1,
       4, 4, 9, 6, 4, 9, 6, 0, 0, 5, 6, 0, 3, 1, 6, 9, 7, 4, 2, 8, 6, 0, 6,
       3, 7,

In [22]:
clf.score(train_image_testimage, train_label_testlabel)

0.86436170212765961

In [23]:
train_label = traindata.iloc[0:2501, 0:1]
train_image = traindata.iloc[0:2501, 1:]
train_image_trainimage, train_image_testimage, train_label_trainlabel, train_label_testlabel = train_test_split(train_image, train_label, random_state=0)

In [24]:
clf = svm.SVC(kernel = 'linear')
clf.fit(train_image_trainimage, train_label_trainlabel.values.ravel())
clf.predict(train_image_testimage)

array([9, 4, 9, 0, 8, 5, 7, 9, 3, 4, 2, 5, 9, 1, 8, 4, 1, 4, 2, 6, 5, 0, 5,
       5, 4, 9, 7, 5, 0, 3, 6, 1, 4, 1, 0, 9, 0, 2, 1, 6, 3, 6, 5, 9, 5, 5,
       7, 0, 8, 0, 6, 0, 4, 7, 8, 3, 5, 5, 9, 2, 7, 6, 8, 5, 6, 8, 2, 2, 9,
       1, 4, 3, 2, 1, 7, 9, 3, 3, 4, 3, 2, 4, 9, 0, 4, 2, 5, 2, 7, 1, 4, 5,
       6, 9, 1, 2, 6, 2, 1, 8, 2, 1, 0, 4, 7, 7, 5, 1, 1, 7, 8, 5, 2, 2, 3,
       6, 7, 1, 8, 1, 5, 7, 9, 3, 6, 6, 2, 0, 7, 5, 8, 7, 7, 9, 0, 6, 3, 2,
       8, 0, 2, 7, 9, 9, 5, 4, 5, 8, 3, 5, 2, 8, 5, 1, 3, 1, 3, 9, 3, 1, 3,
       9, 7, 7, 2, 6, 7, 7, 4, 0, 2, 4, 4, 6, 0, 3, 7, 3, 0, 8, 4, 6, 9, 3,
       3, 1, 8, 1, 2, 1, 3, 3, 2, 2, 3, 8, 6, 8, 5, 5, 6, 3, 0, 9, 0, 4, 9,
       1, 8, 5, 2, 9, 2, 3, 8, 9, 0, 1, 0, 5, 3, 6, 8, 2, 0, 1, 4, 1, 7, 4,
       5, 8, 6, 1, 6, 4, 0, 3, 7, 7, 6, 7, 7, 5, 7, 2, 0, 5, 2, 8, 1, 3, 9,
       1, 6, 0, 0, 0, 9, 7, 8, 8, 3, 5, 2, 5, 4, 0, 1, 6, 1, 0, 0, 3, 7, 6,
       1, 4, 2, 5, 5, 5, 9, 1, 0, 0, 1, 3, 8, 4, 0, 3, 0, 9, 1, 6, 8, 0, 6,
       1, 6,

In [25]:
clf.score(train_image_testimage, train_label_testlabel)

0.88498402555910538

In [26]:
train_label = traindata.iloc[0:15001, 0:1]
train_image = traindata.iloc[0:15001, 1:]
train_image_trainimage, train_image_testimage, train_label_trainlabel, train_label_testlabel = train_test_split(train_image, train_label, random_state=0)

In [27]:
clf = svm.SVC(kernel = 'linear')
clf.fit(train_image_trainimage, train_label_trainlabel.values.ravel())
clf.predict(train_image_testimage)

array([2, 6, 7, ..., 0, 4, 4])

In [28]:
clf.score(train_image_testimage, train_label_testlabel)

0.90909090909090906

In [29]:
train_label = traindata.iloc[0:3001, 0:1]
train_image = traindata.iloc[0:3001, 1:]
train_image_trainimage, train_image_testimage, train_label_trainlabel, train_label_testlabel = train_test_split(train_image, train_label, random_state=0)

In [30]:
clf = svm.SVC(kernel = 'linear')
clf.fit(train_image_trainimage, train_label_trainlabel.values.ravel())
clf.predict(train_image_testimage)

array([3, 8, 7, 1, 8, 5, 7, 8, 6, 1, 1, 2, 0, 2, 1, 6, 9, 4, 8, 7, 7, 6, 0,
       7, 2, 2, 9, 7, 4, 2, 6, 4, 4, 1, 5, 7, 8, 1, 9, 6, 1, 2, 7, 2, 5, 7,
       5, 4, 1, 2, 8, 2, 0, 3, 3, 5, 5, 0, 8, 2, 6, 9, 6, 5, 5, 2, 5, 4, 8,
       1, 4, 2, 5, 7, 3, 6, 9, 4, 9, 1, 4, 8, 2, 7, 6, 7, 4, 5, 6, 2, 7, 0,
       5, 7, 0, 1, 6, 2, 5, 1, 6, 5, 2, 9, 2, 1, 2, 0, 2, 3, 0, 9, 9, 0, 3,
       4, 9, 9, 0, 7, 7, 7, 0, 7, 4, 8, 2, 7, 2, 9, 4, 0, 0, 4, 1, 1, 1, 5,
       4, 9, 0, 2, 8, 1, 9, 4, 1, 0, 7, 7, 6, 5, 4, 0, 6, 0, 0, 2, 1, 3, 6,
       2, 9, 0, 1, 5, 0, 0, 5, 3, 6, 5, 9, 2, 6, 6, 8, 5, 8, 6, 4, 0, 3, 1,
       3, 0, 7, 2, 2, 6, 1, 2, 7, 8, 1, 1, 1, 6, 0, 6, 8, 3, 3, 5, 5, 4, 7,
       1, 6, 3, 2, 6, 8, 7, 1, 0, 5, 4, 9, 9, 1, 2, 1, 1, 2, 8, 3, 2, 4, 2,
       4, 2, 3, 7, 9, 3, 1, 0, 1, 4, 8, 9, 7, 5, 8, 5, 9, 6, 7, 7, 4, 4, 0,
       4, 4, 5, 6, 8, 6, 0, 3, 0, 3, 9, 1, 8, 6, 1, 4, 2, 6, 3, 3, 5, 5, 2,
       5, 9, 1, 3, 6, 2, 6, 2, 4, 7, 5, 2, 6, 8, 4, 9, 4, 6, 1, 7, 4, 1, 0,
       4, 5,

In [31]:
clf.score(train_image_testimage, train_label_testlabel)

0.92276964047936083

In [32]:
testdata = pd.read_csv('/Users/chungpinhsu/Downloads/test.csv')
clf.predict(testdata)

array([2, 0, 9, ..., 3, 9, 2])

In [33]:
results = clf.predict(testdata)
df = pd.DataFrame(results)
df.index.name='ImageId'
df.index+=1
df.columns=['Label']
df.to_csv('results.csv', header=True)