In [1]:
#NumPy tutorial
import numpy as np

In [2]:
#numpy以C語言寫成，運用矩陣計算
array = np.array[[1, 2, 3], [4, 5, 6]]
print(array)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [4]:
#numpy以C語言寫成，運用矩陣計算
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array)

[[1 2 3]
 [4 5 6]]


In [5]:
#get 數據維度, 列欄數, 數據大小等資訊
print('Number of dim', array.ndim)
print('Shape', array.shape)
print('Size', array.size)

Number of dim 2
Shape (2, 3)
Size 6


In [192]:
#Test
test1 = np.array([1, 2, 3])
test2 = np.array([[1, 2, 3]]) #雙[] -> 數據維度變成2
print(test1.ndim)
print(test2.ndim)

1
2


In [7]:
#定義array的type
array2 = np.array([1, 2, 3], dtype = int)
print(array2.dtype)
array2 = np.array([1, 2, 3], dtype = float)
print(array2.dtype)

int64
float64


In [10]:
#創建array
#生成一個全部為0 or 1 or empty的矩陣
#以()來表示所要生成幾列幾欄的矩陣
#也可以定義其dtype
Zero_array = np.zeros((3, 4), dtype = int)
print(Zero_array, Zero_array.dtype)
One_array = np.ones((3, 4))
print(One_array)
#empty是一個接近為零的矩陣，並不等於空
Empty_array = np.empty((3, 4))
print(Empty_array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] int64
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [193]:
#test
Empty_array2 = np.empty([3, 4]) #np.empty(()) & np.empty([]) 都有人用，經測試結果可以
print(Empty_array)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [14]:
#生成有序的矩陣
Arange_array = np.arange(10, 20)
print(Arange_array)
Arange_array2 = np.arange(10, 20, 2)
print(Arange_array2)

[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]


In [16]:
#重新定義矩陣的列欄數
#列欄數一樣用()定義
Arange_array3 = np.arange(12).reshape((3, 4))
print(Arange_array3)
Arange_array4 = np.arange(10, 20).reshape((2, 5))
print(Arange_array4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[10 11 12 13 14]
 [15 16 17 18 19]]


In [178]:
#生成一段數列
Line_array = np.linspace(10, 20)
#把一段數列分成x段
Line_array2 = np.linspace(10, 20, 20)
#也可以把數列reshape
Line_array3 = np.linspace(10, 20, 20).reshape((4, 5))
print(Line_array)
print('Dim of Line_array :', Line_array.ndim)
print(Line_array2)
print(Line_array3)
print('Dim of Line_array3 :', Line_array3.ndim)

[ 10.          10.20408163  10.40816327  10.6122449   10.81632653
  11.02040816  11.2244898   11.42857143  11.63265306  11.83673469
  12.04081633  12.24489796  12.44897959  12.65306122  12.85714286
  13.06122449  13.26530612  13.46938776  13.67346939  13.87755102
  14.08163265  14.28571429  14.48979592  14.69387755  14.89795918
  15.10204082  15.30612245  15.51020408  15.71428571  15.91836735
  16.12244898  16.32653061  16.53061224  16.73469388  16.93877551
  17.14285714  17.34693878  17.55102041  17.75510204  17.95918367
  18.16326531  18.36734694  18.57142857  18.7755102   18.97959184
  19.18367347  19.3877551   19.59183673  19.79591837  20.        ]
Dim of Line_array : 1
[ 10.          10.52631579  11.05263158  11.57894737  12.10526316
  12.63157895  13.15789474  13.68421053  14.21052632  14.73684211
  15.26315789  15.78947368  16.31578947  16.84210526  17.36842105
  17.89473684  18.42105263  18.94736842  19.47368421  20.        ]
[[ 10.          10.52631579  11.05263158  11.5789473

In [179]:
a = np.arange(4)
print(a)
print(a<3)
#numpy矩陣計算分兩種，一種是逐個計算，一個是矩陣計算dot(dot有兩種表示法)
b = np.array([[1, 2], [3, 4]])
c = np.arange(4).reshape((2, 2))
print(b)
print(c)
print(b*c)
print(np.dot(b, c))
print(b.dot(c))

[0 1 2 3]
[ True  True  True False]
[[1 2]
 [3 4]]
[[0 1]
 [2 3]]
[[ 0  2]
 [ 6 12]]
[[ 4  7]
 [ 8 15]]
[[ 4  7]
 [ 8 15]]


In [19]:
#隨機生成一個矩陣
d = np.random.random((2, 4))
print(d)
print(d.sum()) #求加總
print(d.min()) #求最小值
print(d.max()) #求最大值
#列的方向 axis = 1, 欄的方向 axis = 0
print(d.sum(), axis = 1) #求每列加總

[[ 0.98825154  0.63969033  0.32517136  0.4492534 ]
 [ 0.61082961  0.51861172  0.31361913  0.70114802]]
4.54657510439
0.313619126253
0.988251538372


TypeError: 'axis' is an invalid keyword argument for this function

In [20]:
#隨機生成一個矩陣
d = np.random.random((2, 4))
print(d)
print(d.sum()) #求加總
print(d.min()) #求最小值
print(d.max()) #求最大值
#列的方向 axis = 1, 欄的方向 axis = 0
print(d.sum(axis = 1)) #求每列加總

[[ 0.69322602  0.70248387  0.74829774  0.10871559]
 [ 0.29422044  0.77616098  0.28766909  0.77418588]]
4.38495961687
0.108715588954
0.77616098245
[ 2.25272322  2.13223639]


In [180]:
e = np.arange(2, 14).reshape((3, 4))
print(e)
print(e.argmin()) #求最小值的索引值
print(e.argmax())
print(e.cumsum()) #求逐步累加的過程
print(e.diff())   #求各項之間的差
print(e.nonzero())#求非0值的索引值(第x列, 第y欄)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11
[ 2  5  9 14 20 27 35 44 54 65 77 90]


AttributeError: 'numpy.ndarray' object has no attribute 'diff'

In [181]:
e = np.arange(2, 14).reshape((3, 4))
print(e)
print(e.argmin()) #求最小值的索引值
print(e.argmax())
print(e.cumsum()) #求逐步累加的過程
print(np.diff(e)) #求各項之間的差 #diff()可能是較舊的版本因此需要換寫法 
print(e.nonzero())#求非0值的索引值(第x列, 第y欄)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))


In [23]:
f = np.array(14, 2).reshape(3, 4)
print(f)
print(f.sort()) #逐行排序

TypeError: data type not understood

In [26]:
f = np.array(14, 2, -1).reshape(3, 4) #加上-號讓他知道往負方向跑
print(f)
print(f.sort()) #逐行排序

ValueError: only 2 non-keyword arguments accepted

In [191]:
f = np.arange(14, 2, -1).reshape((3, 4)) #加上-號讓他知道往負方向跑
print(f)
print(f.sort()) #逐行排序

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
None


In [190]:
f = np.arange(14, 2, -1).reshape((3, 4)) #加上-號讓他知道往負方向跑
print(f)
print(np.sort(f)) #逐行排序 #sort一樣要改寫

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


In [194]:
#reshpae的差異between reshape() and reshape(())? -> 簡單搜尋一下應該是都可以，視當下情況

In [32]:
#將矩陣反向，列欄互換，有兩種寫法
print(f)
print(f.transpose())
print(f.T)

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


In [33]:
#clip(a, a_min, a_max, out=None)
print(f)
print(np.clip(f, 3, 9)) #a_min = 3 所有小於3的值都等於3, a_max = 9 所有大於9的值都等於9

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[9 9 9 9]
 [9 9 8 7]
 [6 5 4 3]]


In [185]:
g = np.arange(3, 15)
print(g)
print(g[3]) #求索引值3的值
g = np.arange(3, 15).reshape((3, 4))
print('-'*10)
print(g)
print('-'*3)
print(g[2]) #求列索引值 = 2的值，也就是第3列的值
print(g[2][2]) #求列索引值 = 2, 欄索引值 = 2 的值，也就是第3列第3欄的值
print(g[2, 2]) #同上，不同寫法
print(g[:, 1:3])

[ 3  4  5  6  7  8  9 10 11 12 13 14]
6
----------
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
---
[11 12 13 14]
13
13
[[ 4  5]
 [ 8  9]
 [12 13]]


In [186]:
#印出每一列的值
print(g)
for rows in g:
    print(rows)
print('-'*10)
#欄在numpy裡無法迭代，因此換個寫法
print(g)
print(g.T)
for columns in g.T:
    print(columns)
print('-'*10)
#要印出裡面每一項的數字因為也無法迭代，換個寫法
print(g)
print(g.flatten()) #flatten()將矩陣壓平變成數列，而跟flat()的差別在flatten()會返回被改變後的數列
for items in g.flat:
    print(items)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
----------
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[[ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]
 [ 6 10 14]]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
----------
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [188]:
#數列合併
h = np.array([1, 1, 1])
i = np.array([2, 2, 2])
print(h)
print(i)
print('-'*3)
vertical_stack = np.vstack((h, i)) #上下合併
print(vertical_stack)
horizontal_stack = np.hstack((h, i)) #左右合併
print(horizontal_stack)
print('-'*10)
#若想讓h數列從橫變成直
print(h.T, h.T.shape) #用transpose是無效的
#用h.reshpae(0, 1)會出錯
#新增維度
print(h[np.newaxis, :], h[np.newaxis, :].shape)
print(h[:, np.newaxis], h[:, np.newaxis].shape)
print('-'*10)
#變成縱向，左右合併
h = np.array([1, 1, 1])[:, np.newaxis]
i = np.array([2, 2, 2])[:, np.newaxis]
print(np.hstack((h, i)))
print(np.hstack((h, i, i))) #支援多個合併
#concatenate像是vstack, hstack的綜合，在後面指定axis即可
print(np.concatenate((h, i, i), axis = 1))
print(np.concatenate((h, i, i), axis = 0))

[1 1 1]
[2 2 2]
---
[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]
----------
[1 1 1] (3,)
[[1 1 1]] (1, 3)
[[1]
 [1]
 [1]] (3, 1)
----------
[[1 2]
 [1 2]
 [1 2]]
[[1 2 2]
 [1 2 2]
 [1 2 2]]
[[1 2 2]
 [1 2 2]
 [1 2 2]]
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]]


In [189]:
#等量分割
j = np.arange(12).reshape(3, 4)
print(j)
print('-'*3)
print(np.split(j, 3, axis=0)) #split(array, 分成幾等分, axis) #axis=0是在縱向上做分割所以會是水平切，需要思考一下
print('-'*3)
print(np.split(j, 4, axis=1))
print('-'*3)
print(np.vsplit(j, 3)) #vstack的相反
print('-'*3)
print(np.hsplit(j, 2)) #hstack的相反
print('-'*10)
#不等量分割
print(np.array_split(j, 2, axis=0))
print(np.array_split(j, 3, axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
---
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
---
[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
---
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
---
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
----------
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [63]:
#一個array付值給一個變量，他們之間是相等的
k = np.arange(4)
k1 = k
k2 = k1
print(k, k1, k2)
print(k1 is k, k2 is k)
k[0] = 66
print(k, k1, k2)
print(k1 is k, k2 is k)
#要改變k而不影響k1, k2，使用deeppcopy
k = np.arange(4)
k1 = k.copy()
print(k, k1)
print(k1 is k)
k[0] = 66
print(k, k1)
print(k1 is k)

[0 1 2 3] [0 1 2 3] [0 1 2 3]
True True
[66  1  2  3] [66  1  2  3] [66  1  2  3]
True True
[0 1 2 3] [0 1 2 3]
False
[66  1  2  3] [0 1 2 3]
False


In [64]:
#Pandas tutorial

In [66]:
#Pandas相當於字典式NumPy
import pandas as pd

In [68]:
l = pd.Series([1, 2, 55, np.nan, 78]) #想像成np.arange()給每個data一個索引值
print(l)

0     1.0
1     2.0
2    55.0
3     NaN
4    78.0
dtype: float64


In [73]:
dates = pd.date_range('20180101', periods=6)
print(dates)

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06'],
              dtype='datetime64[ns]', freq='D')


In [196]:
df = pd.DataFrame(np.random.randn(6, 4), index = dates, columns = ['a', 'b', 'c', 'd']) #random.random & random.randn差異？
print(df)
print('-'*10)
df2 = pd.DataFrame({'A':1., 'B':pd.Timestamp('20180116'), 'C':pd.Series(1, index = list(range(4)), dtype = float), 'D':np.array([3]*4, dtype = int)})
print(df2)
print(df2.dtypes) #要加上s

                   a         b         c         d
2018-01-01  0.747949 -0.613682  0.836633 -2.023560
2018-01-02 -0.119628 -1.556901 -0.073948  0.031684
2018-01-03 -0.414245 -2.262648 -1.656072 -0.742091
2018-01-04 -0.000977 -0.858583  0.936576  0.336750
2018-01-05  1.176719 -2.682502 -2.144172  0.677620
2018-01-06  1.492953 -1.617939 -1.638110  1.088527
----------
     A          B    C  D
0  1.0 2018-01-16  1.0  3
1  1.0 2018-01-16  1.0  3
2  1.0 2018-01-16  1.0  3
3  1.0 2018-01-16  1.0  3
A           float64
B    datetime64[ns]
C           float64
D             int64
dtype: object


In [197]:
#df2資訊
print(df2.index)
print('-'*3)
print(df2.columns)
print('-'*3)
print(df2.values)
print('-'*3)
print(df2.info) #info()可加可不加？ -> 都可以
print('-'*3)
print(df2.describe)
print('-'*3)
print(df2.T) #反轉df2，列欄互換
print('-'*3)
print(df2.sort_index(axis = 1, ascending=False)) #將欄反向排列
print('-'*3)
print(df2.sort_values(by='C')) #根據C欄排序

Int64Index([0, 1, 2, 3], dtype='int64')
---
Index(['A', 'B', 'C', 'D'], dtype='object')
---
[[1.0 Timestamp('2018-01-16 00:00:00') 1.0 3]
 [1.0 Timestamp('2018-01-16 00:00:00') 1.0 3]
 [1.0 Timestamp('2018-01-16 00:00:00') 1.0 3]
 [1.0 Timestamp('2018-01-16 00:00:00') 1.0 3]]
---
<bound method DataFrame.info of      A          B    C  D
0  1.0 2018-01-16  1.0  3
1  1.0 2018-01-16  1.0  3
2  1.0 2018-01-16  1.0  3
3  1.0 2018-01-16  1.0  3>
---
<bound method NDFrame.describe of      A          B    C  D
0  1.0 2018-01-16  1.0  3
1  1.0 2018-01-16  1.0  3
2  1.0 2018-01-16  1.0  3
3  1.0 2018-01-16  1.0  3>
---
                     0                    1                    2  \
A                    1                    1                    1   
B  2018-01-16 00:00:00  2018-01-16 00:00:00  2018-01-16 00:00:00   
C                    1                    1                    1   
D                    3                    3                    3   

                     3  
A                

In [117]:
dates = pd.date_range('20180101', periods=6)
df = pd.DataFrame(np.arange(24).reshape(6, 4), index = dates, columns = ['A', 'B', 'C', 'D'])
print(df)
print(df['A']) #選取A欄
print(df.A) #功能同上
print('-'*10)
#select by label(都是用標籤):loc
print(df.loc['20180103']) 
print(df.loc[:, ['A', 'B']])
print('-'*10)
#select by position(用索引值):iloc
print(df.iloc[3, 1])
print(df.iloc[3:5, 1:3])
print(df.iloc[[1, 3, 5], 1:3])
print('-'*10)
#mix select:ix
print(df.ix[:, ['A', 'B']])
print('-'*10)
#select by Boolean indexing
print(df[df.A>8])
print(df.B[df.A>8])
print('-'*10)
#新增一欄
df['F'] = np.nan
print(df)

             A   B   C   D
2018-01-01   0   1   2   3
2018-01-02   4   5   6   7
2018-01-03   8   9  10  11
2018-01-04  12  13  14  15
2018-01-05  16  17  18  19
2018-01-06  20  21  22  23
2018-01-01     0
2018-01-02     4
2018-01-03     8
2018-01-04    12
2018-01-05    16
2018-01-06    20
Freq: D, Name: A, dtype: int64
2018-01-01     0
2018-01-02     4
2018-01-03     8
2018-01-04    12
2018-01-05    16
2018-01-06    20
Freq: D, Name: A, dtype: int64
----------
A     8
B     9
C    10
D    11
Name: 2018-01-03 00:00:00, dtype: int64
             A   B
2018-01-01   0   1
2018-01-02   4   5
2018-01-03   8   9
2018-01-04  12  13
2018-01-05  16  17
2018-01-06  20  21
----------
13
             B   C
2018-01-04  13  14
2018-01-05  17  18
             B   C
2018-01-02   5   6
2018-01-04  13  14
2018-01-06  21  22
----------
             A   B
2018-01-01   0   1
2018-01-02   4   5
2018-01-03   8   9
2018-01-04  12  13
2018-01-05  16  17
2018-01-06  20  21
----------
             A   B   C   D


/Users/chungpinhsu/anaconda3/envs/ds/lib/python3.6/site-packages/ipykernel_launcher.py:17: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated


In [128]:
dates = pd.date_range('20180101', periods=6)
df2 = pd.DataFrame(np.arange(24).reshape(6, 4), index = dates, columns = ['A', 'B', 'C', 'D'])
df2.iloc[1, 2] = np.nan
df2.iloc[0, 3] = np.nan
print(df2)
print('-'*10)
#清理缺失值
print(df2.dropna(axis = 1, how = 'any')) #how=['any'->只要有缺失值就刪掉, 'all'->整欄或整列都是缺失值才刪掉]
print(df2.fillna(value = 0))
print('-'*10)
#是否有缺失值
print(df2.isnull())
print(np.any(df2.isnull())) #單純想知道是不是有缺失值
print(np.any(df2.isnull()) == False) #道理同上
print(np.any(df2.isnull()) == True)

             A   B     C     D
2018-01-01   0   1   2.0   NaN
2018-01-02   4   5   NaN   7.0
2018-01-03   8   9  10.0  11.0
2018-01-04  12  13  14.0  15.0
2018-01-05  16  17  18.0  19.0
2018-01-06  20  21  22.0  23.0
----------
             A   B
2018-01-01   0   1
2018-01-02   4   5
2018-01-03   8   9
2018-01-04  12  13
2018-01-05  16  17
2018-01-06  20  21
             A   B     C     D
2018-01-01   0   1   2.0   0.0
2018-01-02   4   5   0.0   7.0
2018-01-03   8   9  10.0  11.0
2018-01-04  12  13  14.0  15.0
2018-01-05  16  17  18.0  19.0
2018-01-06  20  21  22.0  23.0
----------
                A      B      C      D
2018-01-01  False  False  False   True
2018-01-02  False  False   True  False
2018-01-03  False  False  False  False
2018-01-04  False  False  False  False
2018-01-05  False  False  False  False
2018-01-06  False  False  False  False
True
False
True


In [130]:
#pandas導入導出 
#pd.read_csv('name.csv')
#pd.to_csv('newname.csv')
#其他檔案格式均相同

In [137]:
#合併concat
df1 = pd.DataFrame(np.ones((3,4))*0, columns=['a','b','c','d'])
df2 = pd.DataFrame(np.ones((3,4))*1, columns=['a','b','c','d'])
df3 = pd.DataFrame(np.ones((3,4))*2, columns=['a','b','c','d'])
print(df1, df2, df3)
print('-'*10)
print(pd.concat((df1, df1, df3), axis = 0))
print('-'*10)
print(pd.concat((df1, df1, df3), axis = 0, ignore_index = True)) #讓索引值重新排列

     a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0      a    b    c    d
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0      a    b    c    d
0  2.0  2.0  2.0  2.0
1  2.0  2.0  2.0  2.0
2  2.0  2.0  2.0  2.0
----------
     a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
0  2.0  2.0  2.0  2.0
1  2.0  2.0  2.0  2.0
2  2.0  2.0  2.0  2.0
----------
     a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0
5  0.0  0.0  0.0  0.0
6  2.0  2.0  2.0  2.0
7  2.0  2.0  2.0  2.0
8  2.0  2.0  2.0  2.0


In [150]:
#concat的參數之一join = 'outer' or 'inner'
df1 = pd.DataFrame(np.ones((3,4))*0, columns=['a','b','c','d'], index=[1,2,3])
df2 = pd.DataFrame(np.ones((3,4))*1, columns=['b','c','d', 'e'], index=[2,3,4])
print(pd.concat([df1, df2])) #join默認值為outer
print('-'*10)
print(pd.concat([df1, df2], join = 'outer')) #跟上述功能相同，outer將空白的地方填入空缺值
print('-'*10)
print(pd.concat([df1, df2], join = 'inner', ignore_index = True)) #inner只合併兩個df都有的欄位
print('-'*10)
#axis = 1合併
print(pd.concat([df1, df2], axis = 1))
print(pd.concat([df1, df2], axis = 1, join_axes = [df1.index])) #加入join_axes參數定義合併後的index以df1為主

     a    b    c    d    e
1  0.0  0.0  0.0  0.0  NaN
2  0.0  0.0  0.0  0.0  NaN
3  0.0  0.0  0.0  0.0  NaN
2  NaN  1.0  1.0  1.0  1.0
3  NaN  1.0  1.0  1.0  1.0
4  NaN  1.0  1.0  1.0  1.0
----------
     a    b    c    d    e
1  0.0  0.0  0.0  0.0  NaN
2  0.0  0.0  0.0  0.0  NaN
3  0.0  0.0  0.0  0.0  NaN
2  NaN  1.0  1.0  1.0  1.0
3  NaN  1.0  1.0  1.0  1.0
4  NaN  1.0  1.0  1.0  1.0
----------
     b    c    d
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  0.0  0.0
3  1.0  1.0  1.0
4  1.0  1.0  1.0
5  1.0  1.0  1.0
----------
     a    b    c    d    b    c    d    e
1  0.0  0.0  0.0  0.0  NaN  NaN  NaN  NaN
2  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0
3  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0
4  NaN  NaN  NaN  NaN  1.0  1.0  1.0  1.0
     a    b    c    d    b    c    d    e
1  0.0  0.0  0.0  0.0  NaN  NaN  NaN  NaN
2  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0
3  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0


In [155]:
#append, 上下連接df, 無法橫向連接也沒有橫向連接的參數
df1 = pd.DataFrame(np.ones((3,4))*0, columns=['a','b','c','d'])
df2 = pd.DataFrame(np.ones((3,4))*1, columns=['a','b','c','d'])
df3 = pd.DataFrame(np.ones((3,4))*1, columns=['a','b','c','d'])
s1 = pd.Series([1,2,3,4], index=['a','b','c','d'])
print(df1.append(df2, ignore_index = True))
print('-'*10)
print(df1.append([df2, df3], ignore_index = True))
print('-'*10)
print(df1.append(s1, ignore_index = True)) 

     a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0
5  1.0  1.0  1.0  1.0
----------
     a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0
5  1.0  1.0  1.0  1.0
6  1.0  1.0  1.0  1.0
7  1.0  1.0  1.0  1.0
8  1.0  1.0  1.0  1.0
----------
     a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  1.0  2.0  3.0  4.0


In [171]:
#merge
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
'A': ['A0', 'A1', 'A2', 'A3'],
'B': ['B0', 'B1', 'B2', 'B3']})
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
'C': ['C0', 'C1', 'C2', 'C3'],
'D': ['D0', 'D1', 'D2', 'D3']})
print(left)
print(right)
print(pd.merge(left, right, on='key')) #on是在某欄位為主去合併
print('-'*10)
#consider two keys
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
'key2': ['K0', 'K1', 'K0', 'K1'],
'A': ['A0', 'A1', 'A2', 'A3'],
'B': ['B0', 'B1', 'B2', 'B3']})
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
'key2': ['K0', 'K0', 'K0', 'K0'],
'C': ['C0', 'C1', 'C2', 'C3'],
'D': ['D0', 'D1', 'D2', 'D3']})
print(left)
print(right)
print(pd.merge(left, right, on=['key1', 'key2'], indicator = True))  # 默認值how='inner' #可以加indicator參數可以顯示出merge的方式
# how = ['left', 'right', 'outer', 'inner']
print(pd.merge(left, right, on=['key1', 'key2'], how='left', indicator = 'indicator column')) #將indicator欄位重新命名


    A   B key
0  A0  B0  K0
1  A1  B1  K1
2  A2  B2  K2
3  A3  B3  K3
    C   D key
0  C0  D0  K0
1  C1  D1  K1
2  C2  D2  K2
3  C3  D3  K3
    A   B key   C   D
0  A0  B0  K0  C0  D0
1  A1  B1  K1  C1  D1
2  A2  B2  K2  C2  D2
3  A3  B3  K3  C3  D3
----------
    A   B key1 key2
0  A0  B0   K0   K0
1  A1  B1   K0   K1
2  A2  B2   K1   K0
3  A3  B3   K2   K1
    C   D key1 key2
0  C0  D0   K0   K0
1  C1  D1   K1   K0
2  C2  D2   K1   K0
3  C3  D3   K2   K0
    A   B key1 key2   C   D _merge
0  A0  B0   K0   K0  C0  D0   both
1  A2  B2   K1   K0  C1  D1   both
2  A2  B2   K1   K0  C2  D2   both
    A   B key1 key2    C    D indicator column
0  A0  B0   K0   K0   C0   D0             both
1  A1  B1   K0   K1  NaN  NaN        left_only
2  A2  B2   K1   K0   C1   D1             both
3  A2  B2   K1   K0   C2   D2             both
4  A3  B3   K2   K1  NaN  NaN        left_only


In [172]:
# merged by index
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
'B': ['B0', 'B1', 'B2']},
index=['K0', 'K1', 'K2'])
right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
'D': ['D0', 'D2', 'D3']},
index=['K0', 'K2', 'K3'])
print(left)
print(right)
# left_index and right_index
print(pd.merge(left, right, left_index=True, right_index=True, how='outer'))
print(pd.merge(left, right, left_index=True, right_index=True, how='inner'))

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2
     C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3
      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3
     A   B   C   D
K0  A0  B0  C0  D0
K2  A2  B2  C2  D2


In [174]:
# handle overlapping -> 'age'
boys = pd.DataFrame({'k': ['K0', 'K1', 'K2'], 'age': [1, 2, 3]})
girls = pd.DataFrame({'k': ['K0', 'K0', 'K3'], 'age': [4, 5, 6]})
print(pd.merge(boys, girls, on='k', suffixes=['_boy', '_girl'], how='outer')) #suffixes將男女年紀分開

   age_boy   k  age_girl
0      1.0  K0       4.0
1      1.0  K0       5.0
2      2.0  K1       NaN
3      3.0  K2       NaN
4      NaN  K3       6.0


In [198]:
'''Reference:
    https://www.youtube.com/channel/UCdyjiB5H8Pu7aDTNVXTTpcg'''

'Reference:\n    https://www.youtube.com/channel/UCdyjiB5H8Pu7aDTNVXTTpcg'